version: build {build} {branch}

os: Windows Server 2012

environment:
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

install:
  - cmd: java -version

build_script:
  - gradlew build

test_script:
  - gradlew test

cache:
  - C:\Users\appveyor\.m2
